apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: push-ops-data
  namespace: '1021179512470'
  selfLink: /apis/serving.knative.dev/v1/namespaces/1021179512470/services/push-ops-data
  uid: bbb63b7d-cc9e-42ad-8cb9-d8fdfa7b6c04
  resourceVersion: AAY8YtDr9Gw
  generation: 74
  creationTimestamp: '2025-04-08T09:56:57.566070Z'
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    serving.knative.dev/creator: y.matsuura@raksul.com
    serving.knative.dev/lastModifier: s.tomiyama@raksul.com
    run.googleapis.com/build-base-image: asia-northeast1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/build-function-target: appendSpreadSheetRow
    run.googleapis.com/build-name: projects/1021179512470/locations/asia-northeast1/builds/cc7ea2d3-5a8d-4c67-84b8-c5829692e296
    run.googleapis.com/build-source-location: gs://run-sources-done-dtp-deg-asia-northeast1/services/push-ops-data/1755244894.602000.zip#1755244894996857
    run.googleapis.com/build-image-uri: asia-northeast1-docker.pkg.dev/done-dtp-deg/cloud-run-source-deploy/push-ops-data
    run.googleapis.com/operation-id: 94e86924-a5c1-49ff-ba25-ec77ba654a81
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: '1'
    run.googleapis.com/urls: '["https://push-ops-data-1021179512470.asia-northeast1.run.app","https://push-ops-data-rlnzfb7xsa-an.a.run.app"]'
    run.googleapis.com/vpc-access-connector: projects/dtp-deg/locations/asia-northeast1/connectors/dtp-d1-redis-connector
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/base-images: '{"push-ops-data-1":"asia-northeast1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22"}'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: dtp-d1-gateway@done-dtp-deg.iam.gserviceaccount.com
      containers:
      - name: push-ops-data-1
        image: asia-northeast1-docker.pkg.dev/done-dtp-deg/cloud-run-source-deploy/push-ops-data@sha256:facbd67026f026669e650d13c9e7d89d8b405a2fa6b261922fb03fa84e2373be
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        env:  # ここにenvを追加
        - name: REDIS_HOST
          value: 10.111.204.131
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_PASSWORD
          value: '4da92137-5e03-4060-8f7f-7b6c758e17c6'
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
      runtimeClassName: run.googleapis.com/linux-base-image-update
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 74
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2025-08-15T08:02:49.849964Z'
  - type: BaseImageValidated
    status: 'True'
    severity: Info
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2025-08-15T08:02:47.430406Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2025-08-15T08:02:49.814065Z'
  latestReadyRevisionName: push-ops-data-00067-pl6
  latestCreatedRevisionName: push-ops-data-00067-pl6
  traffic:
  - revisionName: push-ops-data-00067-pl6
    percent: 100
    latestRevision: true
  url: https://push-ops-data-rlnzfb7xsa-an.a.run.app
  address:
    url: https://push-ops-data-rlnzfb7xsa-an.a.run.app
