apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: push-ops-data
  namespace: '1021179512470'
  selfLink: /apis/serving.knative.dev/v1/namespaces/1021179512470/services/push-ops-data
  uid: bbb63b7d-cc9e-42ad-8cb9-d8fdfa7b6c04
  resourceVersion: AAY9eHHxI2g
  generation: 97
  creationTimestamp: '2025-04-08T09:56:57.566070Z'
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    serving.knative.dev/creator: y.matsuura@raksul.com
    serving.knative.dev/lastModifier: s.tomiyama@raksul.com
    run.googleapis.com/build-base-image: asia-northeast1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/build-function-target: appendSpreadSheetRow
    run.googleapis.com/build-name: projects/1021179512470/locations/asia-northeast1/builds/af0f77e2-b88f-479d-84f8-c3d4937ef621
    run.googleapis.com/build-source-location: gs://run-sources-done-dtp-deg-asia-northeast1/services/push-ops-data/1756437307.307000.zip#1756437307551509
    run.googleapis.com/build-image-uri: asia-northeast1-docker.pkg.dev/done-dtp-deg/cloud-run-source-deploy/push-ops-data
    run.googleapis.com/operation-id: 29dceb7f-0778-40df-950a-1d28ab84d10f
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: '1'
    run.googleapis.com/urls: '["https://push-ops-data-1021179512470.asia-northeast1.run.app","https://push-ops-data-rlnzfb7xsa-an.a.run.app"]'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/vpc-access-connector: projects/done-dtp-deg/locations/asia-northeast1/connectors/dtp-d1-redis-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/base-images: '{"push-ops-data-1":"asia-northeast1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22"}'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: dtp-d1-gateway@done-dtp-deg.iam.gserviceaccount.com
      containers:
      - name: push-ops-data-1
        image: asia-northeast1-docker.pkg.dev/done-dtp-deg/cloud-run-source-deploy/push-ops-data@sha256:15e0ecd2c1de6357882274b6264ac3e502128561d33bcbb965706cf08494c218
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: REDIS_HOST
          value: 10.58.92.139
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_PASSWORD
          value: 1f92414f-3f42-4977-a3ed-99a1941affbe
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
      runtimeClassName: run.googleapis.com/linux-base-image-update
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 97
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2025-08-29T03:16:17.262440Z'
  - type: BaseImageValidated
    status: 'True'
    severity: Info
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2025-08-29T03:16:15.962928Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2025-08-29T03:16:17.226429Z'
  latestReadyRevisionName: push-ops-data-00089-wjj
  latestCreatedRevisionName: push-ops-data-00089-wjj
  traffic:
  - revisionName: push-ops-data-00089-wjj
    percent: 100
    latestRevision: true
  url: https://push-ops-data-rlnzfb7xsa-an.a.run.app
  address:
    url: https://push-ops-data-rlnzfb7xsa-an.a.run.app
