apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: push-ops-data
  namespace: '1021179512470'
  selfLink: /apis/serving.knative.dev/v1/namespaces/1021179512470/services/push-ops-data
  uid: bbb63b7d-cc9e-42ad-8cb9-d8fdfa7b6c04
  resourceVersion: AAY9ePWg9Hw
  generation: 100
  creationTimestamp: '2025-04-08T09:56:57.566070Z'
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    serving.knative.dev/creator: y.matsuura@raksul.com
    serving.knative.dev/lastModifier: s.tomiyama@raksul.com
    run.googleapis.com/build-base-image: asia-northeast1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/build-function-target: appendSpreadSheetRow
    run.googleapis.com/build-name: projects/1021179512470/locations/asia-northeast1/builds/2095aaac-285a-4487-bbf0-64ab7b7fd37f
    run.googleapis.com/build-source-location: gs://run-sources-done-dtp-deg-asia-northeast1/services/push-ops-data/1756437749.151000.zip#1756437749439056
    run.googleapis.com/build-image-uri: asia-northeast1-docker.pkg.dev/done-dtp-deg/cloud-run-source-deploy/push-ops-data
    run.googleapis.com/operation-id: 39a0dd05-02e8-47c1-8ea2-0af215eb7c3a
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: '1'
    run.googleapis.com/urls: '["https://push-ops-data-1021179512470.asia-northeast1.run.app","https://push-ops-data-rlnzfb7xsa-an.a.run.app"]'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/base-images: '{"push-ops-data-1":"asia-northeast1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22"}'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: dtp-d1-gateway@done-dtp-deg.iam.gserviceaccount.com
      containers:
      - name: push-ops-data-1
        image: asia-northeast1-docker.pkg.dev/done-dtp-deg/cloud-run-source-deploy/push-ops-data@sha256:8e2d8f198eeca18bc04ce8423588477dffa258c4b50811a37040271243d3ccbf
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
      runtimeClassName: run.googleapis.com/linux-base-image-update
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 100
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2025-08-29T03:53:06.600060Z'
  - type: BaseImageValidated
    status: 'True'
    severity: Info
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2025-08-29T03:53:05.324163Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2025-08-29T03:53:06.560060Z'
  latestReadyRevisionName: push-ops-data-00091-8r7
  latestCreatedRevisionName: push-ops-data-00091-8r7
  traffic:
  - revisionName: push-ops-data-00091-8r7
    percent: 100
    latestRevision: true
  url: https://push-ops-data-rlnzfb7xsa-an.a.run.app
  address:
    url: https://push-ops-data-rlnzfb7xsa-an.a.run.app
